package by.sda.stringart.web.controller.util.exception;

public class WrongRightsException extends RuntimeException{

	/**
	 * AutoGenerated Serial version ID
	 */
	private static final long serialVersionUID = 7852553602292932080L;
	
	

}
